# Generated by Django 4.1.5 on 2023-01-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationmodel',
            name='end',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='animationmodel',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
