# Generated by Django 4.2.11 on 2024-05-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="name",
            field=models.CharField(
                default="", help_text="Enter a name of the Scene", max_length=100
            ),
            preserve_default=False,
        ),
    ]
