# Generated by Django 4.2.11 on 2024-05-15 19:51

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import scenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scene_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', django_enumfield.db.fields.EnumField(default=0, enum=scenes.models.CameraType)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('fov', models.FloatField()),
                ('near', models.FloatField()),
                ('far', models.FloatField()),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenes.scene')),
            ],
        ),
    ]
